### ISSUE TITLE
Show only author name

### ISSUE THREAD

**Issue by frostmark** [8398a7/action-slack#107]
Hey. I would like to have the ability to show only `author name` in my notifications (without email). I think would be nice to have a function `author_name` for that

**Comment by 8398a7** [comment]
If you want to customize the format, you are supposed to use custom format.

This is because the number of fields would be too large to accommodate individual requests.
If you have a case where adding the author_name would solve this problem, please suggest it.

If adding this would solve multiple problems, we will consider it.

**Comment by frostmark** [comment]
I just did that `process.env.AS_AUTHOR.replace(/\<.*\>/, '')`
Think we can close the issue
