### ISSUE TITLE
An unidentified error occurs after the node20 update.

### ISSUE THREAD

**Issue by finda-yeongjo** [8398a7/action-slack#251]
**Describe the bug**
The 8398a7/action-slack@v3 module, which was running well, does not work.

**To Reproduce**
```
 - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          author_name: "${{ steps.set-vars.outputs.service_env }} - ${{ env.SERVICE_NAME }}"
          github_base_url: MY_PRIVATE_GITHUB_URL
          status: ${{ job.status }}
          fields: repo,commit,author,ref,took,message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()`
```

Additional Info.
- OS : Amazon Linux 2
- Github:  Github Enterprise  3.10.0 runner server

**Expected behavior**
Run Success

**Screenshots**
```
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node20' is not supported, use 'docker', 'node12' or 'node16' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load 8398a7/action-slack/v3/action.yml
```

**Additional context**
I checked the commit updated to node20. But I think the using node20 is not supported error is a strange behavior.

**Comment by 8398a7** [comment]
Since September 2023, node20 has been supported in GitHub Actions runners. There is a possibility that the action may not work with runners older than that. Could you please confirm the version of the runner you are using? The latest version as of now is v2.313.0.
https://github.com/actions/runner/releases/tag/v2.308.0

Considering GitHub Enterprise (GHE) users, I believe it might be appropriate to handle node20 support in v4 instead of v3. This is something to consider for better compatibility with GHE users.

**Comment by finda-yeongjo** [comment]
I checked the issue. I updated the version of action runner and the problem was solved

Thanks for your help!! @8398a7
